# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShreyanshProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'GoogleMaps'
  pod 'Alamofire', '~> 5.2'
  pod 'AlamofireImage', '~> 4.1'


  # Pods for ShreyanshProject

  target 'ShreyanshProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ShreyanshProjectUITests' do
    # Pods for testing
  end

end
